# Target Table Configs
hoodie.datasource.write.recordkey.field=id
hoodie.datasource.write.precombine.field=created_at
hoodie.datasource.write.partitionpath.field=type
hoodie.datasource.write.hive_style_partitioning=true

# Hive Metastore Sync Configs
hoodie.datasource.hive_sync.enable=true
hoodie.datasource.hive_sync.mode=hms
hoodie.datasource.hive_sync.database=default
hoodie.datasource.hive_sync.table=github_events
hoodie.datasource.hive_sync.metastore.uris=thrift://hive-metastore:9083

# Dynamic Schema Evolution on Read/Write
hoodie.schema.on.read.enable=true
hoodie.datasource.write.reconcile.schema=true

# Table Lifecycle Management & Small-File Compaction
hoodie.metadata.enable=false
hoodie.cleaner.commits.retained=5
hoodie.clustering.inline=true
hoodie.clustering.inline.max.commits=4

# JSON Source & Schema Provider Options
hoodie.streamer.schemaprovider.class=org.apache.hudi.utilities.schema.FilebasedSchemaProvider
hoodie.streamer.schemaprovider.source.schema.file=file:///opt/spark/conf/github-schema.avsc
hoodie.streamer.schemaprovider.target.schema.file=file:///opt/spark/conf/github-schema.avsc

