spark.serializer                                org.apache.spark.serializer.KryoSerializer
spark.sql.catalogImplementation                 hive
spark.sql.hive.convertMetastoreParquet         false
spark.hadoop.hive.metastore.uris                thrift://hive-metastore:9083

# S3A FileSystem Implementation (Endpoint injected dynamically at container startup via docker-compose)
spark.hadoop.fs.s3a.path.style.access           false
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled      true
spark.hadoop.fs.s3a.aws.credentials.provider    com.amazonaws.auth.EnvironmentVariableCredentialsProvider

# Load Hudi and AWS/S3 dependencies automatically on session start
spark.jars.packages                             org.apache.hudi:hudi-spark3.5-bundle_2.12:0.15.0,org.apache.hadoop:hadoop-aws:3.3.4
