coordinator=true
# Workshop simplification: coordinator also executes queries.
# In production, set this to false so the coordinator only schedules work.
node-scheduler.include-coordinator=true
http-server.http.port=8080
query.max-memory=1.5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=1.5GB
discovery-server.enabled=true
discovery.uri=http://presto-server:8080
